name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      
      - name: Install dependencies
        run: yarn workspace "@qar/server" install
      
      - name: Build project
        run: yarn workspace "@qar/server" build
      
      - name: Copy dist to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          source: packages/server/dist
          target: git/Q-A-R/packages/server
      
